Controllers/ArticleController.cs
using AutoMapper;
using BigBlog.Models;
using BigBlog.Models.Db;
using BigBlog.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace BigBlog.Controllers
{
    public class ArticleController : Controller
    {
        private readonly IArticleService _articleService;
        private readonly IMapper _mapper;
        public ArticleController(IArticleService articleService, IMapper mapper)
        {
            _articleService = articleService;
            _mapper = mapper;
        }

        [HttpGet("GetArticleByUserId")]
        [Authorize]
        public async Task<Article> GetArticleByUserId(Guid id)
        {
            return await _articleService.GetArticleByUserId(id);
        }

        [HttpGet("GetAllUsers")]
        [Authorize]
        public async Task<List<Article>> GetAllArticle()
        {
            return await _articleService.GetAllArticle();
        }

        [Authorize]
        [HttpPost("AddArticle")]
        public async Task<IActionResult> AddArticle(AuxilaryArticle articleToCreate)
        {
            Article article = _mapper.Map<Article>(articleToCreate);
            article.TegId = Guid.Parse(articleToCreate.TegCountNumber);

            var claimId = Guid.Parse(User.FindFirst(ClaimTypes.NameIdentifier)?.Value);
            var claimRole = User.FindFirst(ClaimTypes.Role)?.Value;
            ClaimModel claimModel = new ClaimModel() { Id = claimId, RoleName = claimRole };
            
            await _articleService.AddArticle(article, claimModel);
            return Redirect("/Home/ArticleAll");
        }

        [Authorize]
        [HttpPost("EditArticle")]
        public async Task<IActionResult> EditArticle(AuxilaryArticle articleToCreate)
        {
            Article article = _mapper.Map<Article>(articleToCreate);
            article.TegId = Guid.Parse(articleToCreate.TegCountNumber);

            var claimId = Guid.Parse(User.FindFirst(ClaimTypes.NameIdentifier)?.Value);
            var claimRole = User.FindFirst(ClaimTypes.Role)?.Value;
            ClaimModel claimModel = new ClaimModel() { Id = claimId, RoleName = claimRole };

            await _articleService.EditArticle(article, claimModel);
            return Redirect("/Home/ArticleAll");
        }

        [Authorize]
        [HttpPost("DeleteArticle")]
        public async Task<IActionResult> DeleteArticle(AuxilaryArticle articleToCreate)
        {
            Article article = _mapper.Map<Article>(articleToCreate);

            var claimId = Guid.Parse(User.FindFirst(ClaimTypes.NameIdentifier)?.Value);
            var claimRole = User.FindFirst(ClaimTypes.Role)?.Value;
            ClaimModel claimModel = new ClaimModel() { Id = claimId, RoleName = claimRole };

            await _articleService.DeleteArticle(article, claimModel);
            return Redirect("/Home/ArticleAll");
        }


    }
}

Controllers/HomeController.cs
using AutoMapper;
using BigBlog.Models;
using BigBlog.Models.Db;
using BigBlog.Services.Implementations;
using BigBlog.Services.Interfaces;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Security.Claims;

namespace BigBlog.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IAuthService _authService;
        private readonly IUserService _userService;
        private readonly IArticleService _articleService;
        private readonly ICommentService _commentService;
        private readonly IRoleService _roleService;
        private readonly ITegService _tegService;
        private readonly IMapper _mapper;

        public HomeController(ILogger<HomeController> logger, IArticleService articleService, IUserService userService,IMapper mapper ,ICommentService commentService, IRoleService roleService, ITegService tegService)
        {
            _logger = logger;
            _articleService = articleService;
            _commentService = commentService;
            _roleService = roleService;
            _tegService = tegService;
            _userService = userService;
            _mapper = mapper;
        }



        [Authorize]
        public async Task<IActionResult> ArticleAdd()
        {
            var tegs = await _tegService.GetAllTegs();
            ViewBag.Tegs = tegs;
            return View();
        }

        [Authorize]
        public async Task<IActionResult> ArticleAll()
        {
            var articles = await _articleService.GetAllArticle();
            ViewBag.Articles = articles;
            return View();
        }

        [Authorize]
        [Route("Home/ArticleEdit%2F{id}")]
        public async Task<IActionResult> ArticleEdit(string id)
        {
            Guid articleId = Guid.Parse(id);
            var article = await _articleService.GetArticleById(articleId);
            var tegs = await _tegService.GetAllTegs();
            var art = _mapper.Map<AuxilaryArticle>(article);
            art.PossibleTegs = tegs;
            ViewBag.Article = art;

            return View();
        }

        [Authorize]
        [Route("Home/ArticlePage%2F{id}")]
        public async Task<IActionResult> ArticlePage(string id)
        {
            Guid articleId = Guid.Parse(id);
            var article = await _articleService.GetArticleById(articleId);
            ViewBag.Article = article;
            return View();
        }

        [Authorize]
        public async Task<IActionResult> CommentAll()
        {
            var comments = await _commentService.GetAllComments();
            ViewBag.Comments = comments;
            return View();
        }

        [Authorize]
        [Route("Home/CommentEdit%2F{id}")]
        public async Task<IActionResult> CommentEdit(Guid id)
        {
            var comment = await _commentService.GetCommentById(id);
            ViewBag.Comment = comment;
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public async Task<IActionResult> Login(string? returnUrl)
        {
            var x = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            Guid claimId = Guid.Empty;
            if (x != null) { claimId = Guid.Parse(x); }
            var claimRole = User.FindFirst(ClaimTypes.Role)?.Value;

            if (claimId == Guid.Empty || claimRole == null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("ArticleAll");
            }

        }


        public async Task<IActionResult> Register()
        {
            var roles = await _roleService.GetAllRoles();
            ViewBag.Roles = roles;
            return View();
        }

        [Authorize]
        public async Task<IActionResult> RoleAdd()
        {
            return View();
        }

        public async Task<IActionResult> SomethingWrong()
        {
            return View();
        }

        [Authorize]
        public async Task<IActionResult> RoleAll()
        {
            var roles = await _roleService.GetAllRoles();
            ViewBag.Roles = roles;
            return View();
        }

        [Authorize]
        [Route("Home/RoleEdit%2F{id}")]
        public async Task<IActionResult> RoleEdit(uint id)
        {
            var role = await _roleService.GetRoleById(id);
            ViewBag.Role = role;
            return View();
        }

        [Authorize]
        public async Task<IActionResult> TegAdd()
        {
            return View();
        }

        [Authorize]
        [Route("Home/TegEdit%2F{id}")]
        public async Task<IActionResult> TegEdit(Guid id)
        {
            var teg = await _tegService.GetTegById(id);
            ViewBag.Teg = teg;
            return View();
        }

        [Authorize]
        public async Task<IActionResult> TegAll()
        {
            var tegs = await _tegService.GetAllTegs();
            ViewBag.Tegs = tegs;
            return View();
        }

        [Authorize]
        public async Task<IActionResult> UserAll()
        {
            var users = await _userService.GetAllUsers();
            ViewBag.Users = users;
            return View();
        }

        [Authorize]
        [Route("Home/UserEdit%2F{id}")]
        public async Task<IActionResult> UserEdit(Guid id)
        {
            var user = await _userService.GetUserById(id);

            var roles = await _roleService.GetAllRoles();
            var auxUser = _mapper.Map<AuxinaryUser>(user);
            auxUser.PossibleRoles = roles;
            ViewBag.User = auxUser;
            return View();
        }

        [Authorize]
        [Route("Home/UserPage%2F{id}")]
        public async Task<IActionResult> UserPage(Guid id)
        {
            var user = await _userService.GetUserById(id);
            ViewBag.User = user;
            return View();
        }
    }
}

Controllers/RoleController.cs
using BigBlog.Models.Db;
using BigBlog.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using BigBlog.Services.Interfaces;

namespace BigBlog.Controllers
{
    public class RoleController : Controller
    {
        private readonly IRoleService _roleService;
        public RoleController(IRoleService roleService)
        {
            _roleService = roleService;
        }

        [Authorize]
        [HttpGet("GetRoleById")]
        public async Task<Role> GetRoleById(uint id)
        {
            return await _roleService.GetRoleById(id);
        }

        [Authorize]
        [HttpGet("GetAllRoles")]
        public async Task<List<Role>> GetAllRoles()
        {
            return await _roleService.GetAllRoles();
        }

        [Authorize]
        [HttpPost("AddRole")]
        public async Task<IActionResult> AddRole(Role role)
        {
            await _roleService.AddRole(role);
            return Redirect("Home/RoleAll");
        }

        [Authorize]
        [HttpPost("EditRole")]
        public async Task<IActionResult> EditRole(Role role)
        {
            var claimId = Guid.Parse(User.FindFirst(ClaimTypes.NameIdentifier)?.Value);
            var claimRole = User.FindFirst(ClaimTypes.Role)?.Value;


            ClaimModel claimModel = new ClaimModel() { Id = claimId, RoleName = claimRole };

            await _roleService.EditRole(role, claimModel);
            return Redirect("Home/RoleAll");
        }

        [Authorize]
        [HttpPost("DeleteRole")]
        public async Task<IActionResult> DeleteRole(Role role)
        {
            var claimId = Guid.Parse(User.FindFirst(ClaimTypes.NameIdentifier)?.Value);
            var claimRole = User.FindFirst(ClaimTypes.Role)?.Value;
            ClaimModel claimModel = new ClaimModel() { Id = claimId, RoleName = claimRole };

            await _roleService.DeleteRole(role, claimModel);
            return Redirect("Home/RoleAll");
        }
    }
}

Controllers/TegController.cs
using BigBlog.Models;
using BigBlog.Models.Db;
using BigBlog.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace BigBlog.Controllers
{
    public class TegController : Controller
    {
        private readonly ITegService _tegService;
        public TegController(ITegService tegService)
        {
            _tegService = tegService;
        }

        [Authorize]
        [HttpGet("GetTegById")]
        public async Task<Teg> GetTegById(Guid id)
        {
            return await _tegService.GetTegById(id);
        }

        [Authorize]
        [HttpGet("GetAllTegs")]
        public async Task<List<Teg>> GetAllTegs()
        {
            return await _tegService.GetAllTegs();
        }

        [Authorize]
        [HttpPost("AddTeg")]
        public async Task<IActionResult> AddTeg(Teg teg)
        {
            var claimId = Guid.Parse(User.FindFirst(ClaimTypes.NameIdentifier)?.Value);
            var claimRole = User.FindFirst(ClaimTypes.Role)?.Value;
            ClaimModel claimModel = new ClaimModel() { Id = claimId, RoleName = claimRole };

            await _tegService.AddTeg(teg, claimModel);
            return Redirect("Home/TegAll");
        }

        [Authorize]
        [HttpPost("EditTeg")]
        public async Task<IActionResult> EditTeg(Teg teg)
        {
            var claimId = Guid.Parse(User.FindFirst(ClaimTypes.NameIdentifier)?.Value);
            var claimRole = User.FindFirst(ClaimTypes.Role)?.Value;
            ClaimModel claimModel = new ClaimModel() { Id = claimId, RoleName = claimRole };

            await _tegService.EditTeg(teg, claimModel);
            return Redirect("Home/TegAll");
        }

        [Authorize]
        [HttpPost("DeleteTeg")]
        public async Task<IActionResult> DeleteTeg(Teg teg)
        {
            var claimId = Guid.Parse(User.FindFirst(ClaimTypes.NameIdentifier)?.Value);
            var claimRole = User.FindFirst(ClaimTypes.Role)?.Value;
            ClaimModel claimModel = new ClaimModel() { Id = claimId, RoleName = claimRole };

            await _tegService.DeleteTeg(teg, claimModel);
            return Redirect("Home/TegAll");
        }
    }
}

Controllers/UserController.cs
using AutoMapper;
using BigBlog.Models;
using BigBlog.Models.Db;
using BigBlog.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace BigBlog.Controllers
{

    public class UserController : Controller
    {
        private readonly IUserService _userService;
        private readonly IMapper _mapper;
        public UserController(IUserService userService, IMapper mapper)
        {
            _userService = userService;
            _mapper = mapper;
        }

        [Authorize]
        [HttpGet("GetUserById")]
        public async Task<User> GetUserById(Guid id)
        {
            return await _userService.GetUserById(id);
        }

        [Authorize]
        [HttpGet("GetAllUsers")]
        public async Task<List<User>> GetAllUsers()
        {
            return await _userService.GetAllUsers();
        }

        ///Тут нет authorize, ибо это регистрация пользователя
        [HttpPost("AddUser")]
        public async Task<IActionResult> AddUser(AuxinaryUser _user)
        {
            var user = _mapper.Map<User>(_user);
            user.RoleId = uint.Parse(_user.RoleName);

            await _userService.AddUser(user);
            return Redirect("/Home/Login");
        }

        [Authorize]
        [HttpPost("EditUser")]
        public async Task<IActionResult> EditUser(AuxinaryUser _user)
        {

            var user = _mapper.Map<User>(_user);
            user.RoleId = uint.Parse(_user.RoleName);

            var claimId = Guid.Parse(User.FindFirst(ClaimTypes.NameIdentifier)?.Value);
            var claimRole = User.FindFirst(ClaimTypes.Role)?.Value;
            ClaimModel claimModel = new ClaimModel() { Id = claimId, RoleName = claimRole };

            await _userService.EditUser(user, claimModel);
            return Redirect("/Home/UserAll");
        }

        [Authorize]
        [HttpPost("DeleteUser")]
        public async Task<IActionResult> DeleteUser(AuxinaryUser _user)
        {
            var user = _mapper.Map<User>(_user);
            user.RoleId = uint.Parse(_user.RoleName);
            var claimId = Guid.Parse(User.FindFirst(ClaimTypes.NameIdentifier)?.Value);
            var claimRole = User.FindFirst(ClaimTypes.Role)?.Value;
            ClaimModel claimModel = new ClaimModel() { Id = claimId, RoleName = claimRole };

            await _userService.DeleteUser(user, claimModel);
            return Redirect("/Home/UserAll");
        }


    }
}

Views/Home/AccessDenied.cshtml
@{
    ViewData["Title"] = "Нет доступа!";
}

<div class="text-center">
    <p>У вас нет доступа на это действие.</p>
</div>

Views/Home/ArticleAdd.cshtml
@{
    ViewData["Title"] = "Add Article";
}

<div class="text-center">
    <h1 class="display-4">Создайте статью</h1>



    

    <form method="post" asp-controller="Article" asp-action="AddArticle">

        <fieldset>
            <legend>Тег:</legend>
            @foreach (var teg in ViewBag.Tegs)
            {
                var id = teg.Id.ToString();

                <div>
                    <input type="radio" id="@id" name="TegCountNumber" value="@id" checked />
                    <label for="@id">@teg.Name</label>
                </div>
            }


        </fieldset>

        <div>
            <label for="Title">Заголовок статьи:</label>
            <input name="Title" id="Title" required />
        </div>
        <div>
            <label for="Content">Статья:</label>
            <textarea id="Content" name="Content" rows="5" cols="33" required ></textarea>
        </div>
        <div>
            <button>Создать</button>
        </div>
    </form>


</div>

Views/Home/ArticleAll.cshtml
@{
    ViewData["Title"] = "Articles";
    //Все статьи + можно зайти на каждую
}

<div class="text-center">
    <h1 class="display-4">Articles</h1>

    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="ArticleAdd">Создайте свою статью</a>

    @foreach (var article in ViewBag.Articles)
    {
        <div style="border: 3px solid black;">
            <h2>@article.Title</h2>
            <p>@article.Content </p>

            <p>@article.Teg.Name </p>
            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="ArticlePage/@article.Id">Открыть</a>
        </div>
        
    }

    
</div>

Views/Home/CommentAll.cshtml
@{
    ViewData["Title"] = "All Comment";
}

<div class="text-center">
    <h1 class="display-4">Все комментарии</h1>

    @{
        var claimss = User.Claims.ToList();
        var claimRole = claimss[0];
        var claimUserId = claimss[1];
    }

    @foreach (var comment in ViewBag.Comments)
    {
        <div style="border: 3px solid black;">
            <p>@comment.Text</p>
            @{
                var userId = comment.UserId.ToString();
                var commentId = comment.Id.ToString();
            }

            @if (claimRole.Value == "Администратор" || claimRole.Value == "Модератор" || claimUserId.Value == userId)
            {
                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="CommentEdit/@commentId">Изменить</a>
            }


        </div>
    }

</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Home/NotFound.cshtml
@{
    ViewData["Title"] = "Ресурс не найден";
}

<div class="text-center">
    <p>Ресурс не найден.</p>
</div>

Views/Home/Register.cshtml
@{
    ViewData["Title"] = "Register";
    //Регистрация. После регистации редирект на дефолтную
}

<div class="text-center">
    <h1 class="display-4">Регистиация</h1>

    <form method="post" asp-controller="User" asp-action="AddUser">

        <fieldset>
            <legend>Роли:</legend>
            @foreach (var role in ViewBag.Roles)
            {
                var id = role.Id.ToString();
                var name = role.Name;

                <div>
                    <input type="radio" id="@id" name="RoleName" value="@id" checked />
                    <label for="@id">@name</label>
                </div>
            }


        </fieldset>

        <div>
            <label for="FirstName">Введите ваше имя</label>
            <input name="FirstName" id="FirstName" required />
        </div>
        <div>
            <label for="LastName">Введите вашу фамилию</label>
            <input name="LastName" id="LastName" required />
        </div>
        <div>
            <label for="Email">Введите вашу почту</label>
            <input name="Email" type="email" id="Email" required />
        </div>
        <div>
            <label for="Password">Введите пароль</label>
            <input name="Password" id="Password" required />
        </div>
        <div>
            <button>Регистрация</button>
        </div>
    </form>

    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Login">Есть аккаунт? Войдите!</a>
</div>

Views/Home/RoleAdd.cshtml
@{
    ViewData["Title"] = "Role add";
}

<div class="text-center">
    <h1 class="display-4">Добавить Роль</h1>
    <form method="post" asp-controller="Role" asp-action="AddRole">
        <div>
            <label for="Name">Название Роли:</label>
            <input name="Name" id="Name" required />
        </div>
        <div>
            <label for="Description">Описание Роли:</label>
            <textarea id="Description" name="Description" rows="10" cols="40" required></textarea>
        </div>
        <div>
            <button>Создать</button>
        </div>
    </form>
</div>

Views/Home/RoleAll.cshtml
@{
    ViewData["Title"] = "Role All";
}

<div class="text-center">
    <h1 class="display-4">Роли!</h1>

    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="RoleAdd">Добавить Роль</a>

    @{
        var claimss = User.Claims.ToList();
        var claimRole = claimss[0];
        var claimUserId = claimss[1];
    }

    @foreach (var role in ViewBag.Roles)
    {
        <div style="border: 3px solid black;">
            <h2>@role.Name</h2>
            <p>@role.Description </p>



            @if(role.Id>3)
            {
                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="RoleEdit/@role.Id">Изменить</a>
            }

        </div>

    }
</div>

Views/Home/RoleEdit.cshtml
@{
    ViewData["Title"] = "RoleEdit";
}

<div class="text-center">
    @{
        var claimss = User.Claims.ToList();
        var claimRole = claimss[0];
        var claimUserId = claimss[1];
    }

    <form method="post" asp-controller="Role" asp-action="DeleteRole">


        <input type="hidden" name="Name" id="Name" value="@ViewBag.Role.Name" />
        <input type="hidden" name="Description" id="Description" value="@ViewBag.Role.Description" />
        <input type="hidden" name="Id" value="@ViewBag.Role.Id" />

        <div>
            <button>Удалить роль</button>
        </div>
    </form>

    <form method="post" asp-controller="Role" asp-action="EditRole">
        <div>
            <label for="Name">Название роли</label>
            <input name="Name" id="Name" value="@ViewBag.Role.Name" required />
        </div>
        <div>
            <label for="Description">Описание роли</label>
            <input name="Description" id="Description" value="@ViewBag.Role.Description" required />
        </div>

        <input type="hidden" name="Id"  value="@ViewBag.Role.Id" />

        <div>
            <button>Изменить</button>
        </div>
    </form>
</div>

Views/Home/Something wrong.cshtml
@{
    ViewData["Title"] = "Something wrong";
}

<div class="text-center">
    <p>что-то пошло не так.</p>
</div>

Views/Home/TegAdd.cshtml
@{
    ViewData["Title"] = "Add Teg";
}

<div class="text-center">
    <h1 class="display-4">Добавить Тег</h1>

    <form method="post" asp-controller="Teg" asp-action="AddTeg">
        <div>
            <label for="Name">Тег:</label>
            <input name="Name" id="Name" required />
        </div>
        <div>
            <button>Создать</button>
        </div>
    </form>
</div>

Views/Home/TegEdit.cshtml
@{
    ViewData["Title"] = "Teg Edit";
}

<div class="text-center">
    @{
        var claimss = User.Claims.ToList();
        var claimRole = claimss[0];
        var claimUserId = claimss[1];
        var namestring = claimUserId.Value.ToString();
    }



    <form method="post" asp-controller="Teg" asp-action="DeleteTeg">
        <input type="hidden" name="Name" value="@ViewBag.Teg.Name" />
        <input type="hidden" name="Id" value="@ViewBag.Teg.Id" />
        <input type="hidden" name="UserId" value="@claimUserId.Value"
        <div>
            <button>Удалить</button>
        </div>
    </form>

    <form method="post" asp-controller="Teg" asp-action="EditTeg">
        <div>
            <label for="Name">Тег:</label>
            <input name="Name" id="Name" required />
        </div>


        <input type="hidden" name="Id" value="@ViewBag.Teg.Id" />
        <input type="hidden" name="UserId" value="@claimUserId.Value"
        <div>
            <button>Изменить</button>
        </div>
    </form>

</div>

Views/Home/UserEdit.cshtml
@{
    ViewData["Title"] = "Edit User";
    //Можно редачить и удалять пользователя
}

<div class="text-center">

    @{
        var claimss = User.Claims.ToList();
        var claimRole = claimss[0];
        var claimUserId = claimss[1];

    }

    <form method="post" asp-controller="User" asp-action="DeleteUser">

        <input type="hidden" name="Id" value="@ViewBag.User.Id" />
        <input type="hidden" name="FirstName" value="@ViewBag.User.FirstName" />
        <input type="hidden" name="LastName" value="@ViewBag.User.LastName" />
        <input type="hidden" name="Email" value="@ViewBag.User.Email" />
        <input type="hidden" name="Password" value="@ViewBag.User.Password" />
        <input type="hidden" name="RoleName" value="@ViewBag.User.RoleId" />

        <div>
            <button>Удалить пользователя!</button>
        </div>
    </form>
    <form method="post" asp-controller="User" asp-action="EditUser">

        <input type="hidden" name="Id" value="@ViewBag.User.Id" />

        <fieldset>
            <legend>Роли:</legend>
            @foreach (var role in ViewBag.User.PossibleRoles)
            {
                var id = role.Id.ToString();
                var name = role.Name;

                <div>
                    <input type="radio" id="@id" name="RoleName" value="@id" checked />
                    <label for="@id">@name</label>
                </div>
            }


        </fieldset>

        <div>
            <label for="FirstName">Введите ваше имя</label>
            <input name="FirstName" id="FirstName" value="@ViewBag.User.FirstName" required />
        </div>
        <div>
            <label for="LastName">Введите вашу фамилию</label>
            <input name="LastName" id="LastName" value="@ViewBag.User.LastName" required />
        </div>
        <div>
            <label for="Email">Введите вашу почту</label>
            <input name="Email" type="email" id="Email" value="@ViewBag.User.Email" required />
        </div>
        <div>
            <label for="Password">Введите пароль</label>
            <input name="Password" id="Password" value="@ViewBag.User.Password" required />
        </div>
        <div>
            <button>Изменить</button>
        </div>
    </form>



</div>